### PR TITLE
Add ESM module using conditional exports

### LINKED ISSUE #8: allow dual use cjs and esm
Currently, any build of svg-line-chart is targeting nodejs14 and commonjs: https://github.com/rugpullindex/svg-line-chart/blob/f205d99c088033e1b7d0a6732e4d948628f25d33/package.json#L8

However, there's an option that allows making modules available under `/esm` path. For a guide, see option 2: https://2ality.com/2019/10/hybrid-npm-packages.html

Deliverables:

- Preserve the option to import svg-line-chart as commonjs
- Add an option to import svg-line-chart under `/esm` as an ECMAScript module

### PR DESCRIPTION
**Pull request by il3ven**
This PR adds support for both CommonJS and ES Modules. Resolves #8 

Implementation reference -
https://2ality.com/2019/10/hybrid-npm-packages.html#option-1-(experimental%2C-needs-conditional-exports)%3A-esm-and-commonjs-are-both-bare-imports

### CODE REVIEW

**Comment by il3ven** [comment]
@TimDaub

**Review by TimDaub — COMMENTED** [review]
Thanks for your contribution!

In #8 I favored using "option 2" for higher compatibility. I'd like to avoid for users of this library having to set the experimental flag `experimental-conditional-exports`.

What's the reason that you've favored option 1 over option 2 that promises further compatibility?

**Comment by il3ven** [comment]
When the issue mentioned 'option 2' I thought it meant 2.x.

I didn't notice the caveat.😅 A reason for implementing option 2.1 was that 2.2 seemed hacky with more than one package.json.

I tested things after implementation and didn't have to add the experimental flag. Otherwise I wouldn't have missed the caveat.

After some digging, I found that the flag has been removed for node 12.x+. (nodejs/node#31001) Currently I have tested on node v12.22.6 and node v14.17.6. Everything works fine without any warnings.

I say we stick with option 2.1. If you think otherwise then I can make changes to this PR.

**Review by TimDaub — APPROVED** [review]

**Comment by TimDaub** [comment]
Thanks for digging. Supporting node >= 12 is sufficient.

**Pull request merged**
